vich_uploader:
    db_driver: orm

    mappings:
        pages_image:
            uri_prefix: /images/pages
            upload_destination : '%kernel.project_dir%/public/images/pages'
          
            
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
